
print("Enter your details to make your details card.....")
print("Enter your Firstname ")
Firstame=input()
print("Enter your Lastname ")
Lastame=input()
print("Enter your address")
Address=input()
print("Enter your number")
Number=int(input())
print("You details card:")
print("Fullname:"+Firstame+" "+Lastame)
print("Address:"+Address)
print("Number:",Number)
